### PR TITLE
Add commands for manipulating panels.

### PR DESCRIPTION
**Pull request by withoutboats**

### CODE REVIEW

**Comment by waynr** [comment]
If I have any say as to whether or not this gets merged, then I would like to block until there are at least some doc strings on these commands to help me and other new contributors understand what their intent is and what the significance is when they are changed in the future. For example, what situation calls for a panel to be pushed or popped?

Also, what do you think about generalizing the panel protocol in a way that makes splitting a special case of panel creation--so panels can  be create in arbitrary subsections of the screen, ie:

```
.--------------------------------.
|                                |
|                                |
|     .---------------.          |
|     |Panel 1        |          |
|     |  .---------------.       |
|     |  | Panel 2       |       |
|     |  |               |       |
|     |  |               |       |
|     |  |               |       |
|     |  |               |       |
|     '--|               |       |
|        |               |       |
|        '---------------'       |
|                                |
'--------------------------------'
```

I imagine that conceptualizing tui primitives like this in the notty protocol would be especially useful for applications that need to implement their own widgetry. If applications have to implement their own tui primitives then it seems to me like performance benefits of panels is somewhat lessened.

**Comment by withoutboats** [comment]
> Also, what do you think about generalizing the panel protocol in a way that makes splitting a special case of panel creation--so panels can be create in arbitrary subsections of the screen, ie:

I considered this, but decided against it for now. The implementation of creating panels in arbitrary sections is not that complicated, but it would make everything else about how the grid works much more complicated. I'm going to reference your diagram because it is a good example, and I will also the unlabeled background area of the terminal as `Panel 0`.
- Iterating over the visible cells in a grid would become much more complicated. The current implementation guarantees that exactly one or zero rectangular portions of each existing `CharGrid` are visible. As you can see in your diagram, the visible portions of `Panel 1` and `Panel 0` are much more complex.
- The "Ring" structure exposes a simple API, in which you can add a panel above the current one, remove the current one, or rotate up and down the ring. In this structure, from bottom to top, the stack of panels is `[Panel 0, Panel 1, Panel 2]`. If I want to bring `Panel 1` to the foreground, I want the stack of visibility to be `[Panel 0, Panel 2, Panel 1]`, because I want the portion of `Panel 2` not covered by `Panel 1` to be visible. This requires reordering the stack, rather than rotating through it, which would also require a tag for each individual panel in the stack, something the current implementation doesn't have.

Though the high level library that will rest on top of these commands on the other side of the tty has not been built, I think this more limited implementation will make for a much simpler API for users as well.

I'm not set in stone about this though, and I'm especially willing to revisit if the user API for it would not be difficult to use (the implementation, even if its complicated, only has to be written once after all). That said the only time I ever see a TUI that isn't covered by splitting panels is when I'm installing an OS and the installer tries to mimic the look and feel of a GUI before X is installed. Terminal apps that I use day to day like vim and tmux all use splits.

**Comment by withoutboats** [comment]
> If I have any say as to whether or not this gets merged, then I would like to block until there are at least some doc strings on these commands to help me and other new contributors understand what their intent is and what the significance is when they are changed in the future. For example, what situation calls for a panel to be pushed or popped?

Thanks, I need a new task now this is written. For my next project, I'll work on documenting not just these, but all the commands in notty-encoding.

**Comment by waynr** [comment]
I don't think I'm invested enough to argue for the approach I suggested before. I am :+1: on this as-is.

**Comment by withoutboats** [comment]
Cool. I'm very open to returning to this later and adding this feature, it just adds a lot of complication and I'd rather do this in steps.

**Pull request merged**
